version: 2

updates:
  - package-ecosystem: gradle
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: "Africa/Cairo"
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: "chore(deps)"
      include: scope
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    groups:
      gradle-patch:
        update-types:
          - patch
      gradle-minor:
        update-types:
          - minor

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: "Africa/Cairo"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "chore(ci)"
    groups:
      actions-non-breaking:
        update-types:
          - minor
          - patch
      actions-major:
        update-types:
          - major
